#exchange_config.py
import ccxt

# Define your exchanges API keys here
# 01
BINANCE_API_KEY = 'YOUR_BINANCE_API_KEY'
BINANCE_SECRET_KEY = 'YOUR_BINANCE_SECRET_KEY'
# 02
KUCOIN_API_KEY = 'YOUR_KRAKEN_API_KEY'
KUCOIN_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 03
OKX_API_KEY = 'YOUR_KRAKEN_API_KEY'
OKX_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 04
POLONIEX_API_KEY = 'YOUR_KRAKEN_API_KEY'
POLONIEX_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 05
COINEX_API_KEY = 'YOUR_KRAKEN_API_KEY'
COINEX_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 06
BYBIT_API_KEY = 'YOUR_KRAKEN_API_KEY'
BYBIT_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 07
MEXC_API_KEY = 'YOUR_KRAKEN_API_KEY'
MEXC_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 08
UPBIT_API_KEY = 'YOUR_KRAKEN_API_KEY'
UPBIT_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 09
BINGX_API_KEY = 'YOUR_KRAKEN_API_KEY'
BINGX_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 10
GEMINI_API_KEY = 'YOUR_KRAKEN_API_KEY'
GEMINI_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 11
DEEPCOIN_API_KEY = 'YOUR_KRAKEN_API_KEY'
DEEPCOIN_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'
# 12
XT_API_KEY = 'YOUR_KRAKEN_API_KEY'
XT_SECRET_KEY = 'YOUR_KRAKEN_SECRET_KEY'



